# Generated by Django 5.1.11 on 2025-09-02 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hubspot_user_id', models.CharField(blank=True, max_length=100)),
                ('portal_id', models.CharField(blank=True, max_length=100)),
                ('hub_id', models.CharField(blank=True, max_length=100)),
                ('hub_domain', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('expired', 'Token Expired')], default='disconnected', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('auto_sync_contacts', models.BooleanField(default=True)),
                ('sync_company_data', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HubSpot Account',
                'verbose_name_plural': 'HubSpot Accounts',
            },
        ),
        migrations.CreateModel(
            name='HubSpotContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('hubspot_contact_id', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('updated', 'Updated')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error_message', models.TextField(blank=True)),
                ('first_email_date', models.DateTimeField(blank=True, null=True)),
                ('last_email_date', models.DateTimeField(blank=True, null=True)),
                ('total_emails_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hubspot_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='hubspot_integration.hubspotaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['email_address'], name='hubspot_int_email_a_1c6e08_idx'), models.Index(fields=['hubspot_contact_id'], name='hubspot_int_hubspot_ee9042_idx'), models.Index(fields=['sync_status'], name='hubspot_int_sync_st_95e272_idx')],
                'unique_together': {('hubspot_account', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='HubSpotSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('create_contact', 'Create Contact'), ('update_contact', 'Update Contact'), ('create_company', 'Create Company'), ('token_refresh', 'Token Refresh')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('retry', 'Retry')], max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('hubspot_contact_id', models.CharField(blank=True, max_length=100)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
                ('processing_duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hubspot_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='hubspot_integration.hubspotaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hubspot_account', '-created_at'], name='hubspot_int_hubspot_66190c_idx'), models.Index(fields=['operation_type', 'status'], name='hubspot_int_operati_dd09a1_idx'), models.Index(fields=['contact_email'], name='hubspot_int_contact_5c3453_idx')],
            },
        ),
    ]
