# Generated by Django 5.1.11 on 2025-09-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspotaccount',
            name='hub_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
