# Generated by Django 5.1.11 on 2025-09-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_integration', '0002_alter_hubspotaccount_hub_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspotcontact',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hubspotcontact',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
