# Generated by Django 5.1.11 on 2025-09-01 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_remove_invitation_company_remove_user_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable AI processing for this user')),
                ('auto_reply_enabled', models.BooleanField(default=False, help_text='Enable automated replies')),
                ('default_prompt', models.TextField(default='You are a professional email assistant. Analyze the email and draft a helpful, polite, and appropriate response. Be concise but complete in your response.', help_text='Default prompt for AI processing')),
                ('max_response_length', models.IntegerField(default=500, help_text='Maximum length of AI-generated responses')),
                ('response_tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('formal', 'Formal'), ('casual', 'Casual')], default='professional', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Processing Settings',
                'verbose_name_plural': 'AI Processing Settings',
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('prompt_text', models.TextField(help_text='AI prompt template')),
                ('email_keywords', models.TextField(blank=True, help_text='Keywords that trigger this template (comma-separated)')),
                ('sender_patterns', models.TextField(blank=True, help_text='Sender email patterns (comma-separated)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority templates are checked first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmailProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processing_type', models.CharField(choices=[('analysis', 'Analysis Only'), ('reply_generation', 'Reply Generation'), ('auto_reply', 'Automated Reply')], default='analysis', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('ai_analysis', models.JSONField(blank=True, help_text='AI analysis results', null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated email summary')),
                ('ai_sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('urgent', 'Urgent')], max_length=20)),
                ('ai_category', models.CharField(blank=True, help_text='AI-detected email category', max_length=100)),
                ('ai_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20)),
                ('generated_reply_subject', models.CharField(blank=True, max_length=500)),
                ('generated_reply_body', models.TextField(blank=True)),
                ('reply_sent', models.BooleanField(default=False)),
                ('reply_sent_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration', models.FloatField(blank=True, help_text='Processing duration in seconds', null=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='AI tokens consumed', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='User.emailmessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_message', '-created_at'], name='Ai_processi_email_m_eac792_idx'), models.Index(fields=['status', 'processing_type'], name='Ai_processi_status_54a6ae_idx'), models.Index(fields=['reply_sent'], name='Ai_processi_reply_s_75ce52_idx')],
            },
        ),
    ]
