# Generated by Django 5.1.11 on 2025-09-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_processing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIPromptTemplate',
        ),
    ]
