# Generated by Django 5.1.11 on 2025-09-01 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='message_type',
            field=models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('reply', 'Reply')], default='received', max_length=20),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='parent_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='User.emailmessage'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
