# Generated by Django 5.1.11 on 2025-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_invitation_company_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='has_ai_reply',
            field=models.BooleanField(default=False),
        ),
    ]
